force-app/force-app/force-app/main/default/objects/Customers_Planned__c/Customers_Planned__c.object-meta.xml
<CustomObject>
    <label>Customers Planned</label>
    <nameField>
        <displayFormat>PC-{0000}</displayFormat>
        <label>Planned Customers Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customers Planned</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/force-app/force-app/main/default/objects/Customers_Planned__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Billing_District__c</field>
            <operation>equals</operation>
            <valueField>$Source.Place__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customers Planned</relationshipLabel>
    <relationshipName>Customers_Planned</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/force-app/force-app/main/default/objects/Customers_Planned__c/fields/Place__c.field-meta.xml
<CustomField>
    <fullName>Place__c</fullName>
    <label>Place</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Adilabad</fullName>
            </value>
            <value>
                <fullName>Anantapur</fullName>
            </value>
            <value>
                <fullName>Chittoor</fullName>
            </value>
            <value>
                <fullName>East Godavari</fullName>
            </value>
            <value>
                <fullName>Alluri Sitarama Raju</fullName>
            </value>
            <value>
                <fullName>Anakapalli</fullName>
            </value>
            <value>
                <fullName>Annamaya</fullName>
            </value>
            <value>
                <fullName>Bapatla</fullName>
            </value>
            <value>
                <fullName>Eluru</fullName>
            </value>
            <value>
                <fullName>Guntur</fullName>
            </value>
            <value>
                <fullName>Kadapa</fullName>
            </value>
            <value>
                <fullName>Kakinada</fullName>
            </value>
            <value>
                <fullName>Konaseema</fullName>
            </value>
            <value>
                <fullName>Krishna</fullName>
            </value>
            <value>
                <fullName>Kurnool</fullName>
            </value>
            <value>
                <fullName>Manyam</fullName>
            </value>
            <value>
                <fullName>N T Rama Rao</fullName>
            </value>
            <value>
                <fullName>Nandyal</fullName>
            </value>
            <value>
                <fullName>Nellore</fullName>
            </value>
            <value>
                <fullName>Palnadu</fullName>
            </value>
            <value>
                <fullName>Prakasam</fullName>
            </value>
            <value>
                <fullName>Sri Balaji</fullName>
            </value>
            <value>
                <fullName>Sri Satya Sai</fullName>
            </value>
            <value>
                <fullName>Srikakulam</fullName>
            </value>
            <value>
                <fullName>Visakhapatnam</fullName>
            </value>
            <value>
                <fullName>Vizianagaram</fullName>
            </value>
            <value>
                <fullName>West Godavari</fullName>
            </value>
            <value>
                <fullName>Baksa</fullName>
            </value>
            <value>
                <fullName>Barpeta</fullName>
            </value>
            <value>
                <fullName>Bongaigaon</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/force-app/force-app/main/default/objects/Customers_Planned__c/fields/Tour_Plan__c.field-meta.xml
<CustomField>
    <fullName>Tour_Plan__c</fullName>
    <label>Tour Plan</label>
    <referenceTo>Tour_Plan__c</referenceTo>
    <relationshipLabel>Customers Planned</relationshipLabel>
    <relationshipName>Customers_Planned</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/force-app/force-app/main/default/objects/Tour_Plan__c/Tour_Plan__c.object-meta.xml
<CustomObject>
    <label>Tour Plan</label>
    <nameField>
        <displayFormat>TP-{00000}</displayFormat>
        <label>Tour Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tour Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/force-app/force-app/main/default/objects/Tour_Plan__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Billing_District__c</field>
            <operation>equals</operation>
            <valueField>$Source.District__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Tour Plans</relationshipLabel>
    <relationshipName>Tour_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/force-app/force-app/main/default/classes/TourPlanController.cls
public class TourPlanController {
    @AuraEnabled(cacheable=true)
    public static list<String> getCustomers(String recordId){
        system.debug('recordId'+recordId);
        List<Tour_Plan__c> tourPlan = [SELECT Id, Name, Customer__c, District__c from Tour_Plan__c WHERE Id =: recordId];
       List<Account> query = [SELECT Id, Name from Account WHERE Billing_District__c =: tourPlan[0].District__c];
        List<String> customerNames = new List<String>();
        for (Account acc : query){
            customerNames.add(acc.name);
        }
        system.debug('customerNames'+customerNames);
        return customerNames;    
    }
     @AuraEnabled(cacheable=true)
    public static Tour_Plan__c getTourPlan(String recordId){
        List<Tour_Plan__c> tourPlan = [SELECT Name, District__c from Tour_Plan__c WHERE Id =: recordId];
       
        return tourPlan[0];    
    }
    @AuraEnabled
    public static Integer insertPlannedCustomers(List<String> accountNames,String recordId) {
          SYSTEM.DEBUG('recordId'+recordId);
         List<Tour_Plan__c> tourPlan = [SELECT Id, Name,Customer__c,District__c from Tour_Plan__c WHERE Id =: recordId];
        SYSTEM.DEBUG('recordId'+tourPlan);
        List<Account> queriedAccounts = [SELECT Id, Name, Billing_District__c FROM Account WHERE Name IN :accountNames AND Billing_District__c = :tourPlan[0].District__c];
        List<Customers_Planned__c> cpList = new List<Customers_Planned__c>();
        for(Account acc : queriedAccounts){
            Customers_Planned__c cp = new Customers_Planned__c();
            cp.Customer__c = acc.Id;
            cp.Place__c = tourPlan[0].District__c;
            cp.Tour_Plan__c = recordId;
            cpList.add(cp);
        }
        Insert cpList;
        return cpList.size();
        
        
    }
    @AuraEnabled(cacheable=false)
     public static List<String> searchAllCustomers(String searchString,String recordId){
         List<Tour_Plan__c> tourPlan = [SELECT Id, Name, Customer__c, District__c from Tour_Plan__c WHERE Id =: recordId];
       List<Account> query = [SELECT Id, Name from Account WHERE Billing_District__c =: tourPlan[0].District__c];
        List<String> customerNames = new List<String>();
        for (Account acc : query){
            customerNames.add(acc.name);
        }
        List<String> availableObjects = customerNames;
        List<String> matchingObjects = new List<String>();
        String searchStringLower = searchString.toLowerCase();
        
        for (String objectName : availableObjects) {
            if (objectName.toLowerCase().startsWith(searchStringLower)) {
                matchingObjects.add(objectName);
            }
        }
        
        return matchingObjects;
    }
}