force-app/force-app/force-app/main/default/objects/Account/fields/BankAccount__c.field-meta.xml
<CustomField>
    <fullName>BankAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Bank Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>BankAccount__c.Name</field>
            <operation>notEqual</operation>
            <value>NULL</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BankAccount__c</referenceTo>
    <relationshipLabel>Customers</relationshipLabel>
    <relationshipName>Customers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/force-app/force-app/main/default/objects/BankAccount__c/BankAccount__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <label>BankAccount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/force-app/force-app/main/default/objects/Quote/fields/BankAccount__c.field-meta.xml
<CustomField>
    <fullName>BankAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BankAccount</label>
    <referenceTo>BankAccount__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/force-app/force-app/main/default/objects/Quote/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/force-app/force-app/main/default/classes/EM_UtilOrder.cls
@isTest
public class EM_UtilOrder {
	public static BankAccount__c buildBankAccount(String bankName){
        return new BankAccount__c(Name = bankName);
    }
    public static Account buildAccountWithBankAccount(String accName, Id bankId){
        return new Account(Name = accName, BankAccount__c = bankId);
    }
    public static Contact buildContact(String conFirstName,String conLastName,String email,Id accId){
        return new Contact (FirstName = conFirstName,LastName = conLastName,Email = email, AccountId = accId);
    }
    
    public static Contact buildContactWithOutEmail(String conFirstName,String conLastName,Id accId){
        return new Contact (FirstName = conFirstName,LastName = conLastName,AccountId = accId);
    }
    public static Opportunity buildOpportunity(String oppName,Date CloseDate,Id accId,String StageName){
        return new Opportunity(Name = oppName,CloseDate = CloseDate,AccountId = accId,StageName = StageName );
    }
    
    public static Quote buildQuote(String quoteName,Id oppId,Id contactId){
        return new Quote(Name = quoteName,OpportunityId = oppId,ContactId = contactId);
    }
    public static Order buildOrder(Id accId,Id OppId, Id quoteId, Date startDate, String status){
        return new Order(AccountId = accId,OpportunityId = OppId,QuoteId = quoteId, Status = status, EffectiveDate = startDate);        
    }
    public static ContentVersion buildContentVersion(String Title,String PathOnClient,Blob VersionData){
        return new ContentVersion(Title = Title,PathOnClient = PathOnClient,VersionData = VersionData);
    }
    public static ContentDocumentLink buildContentDocumentLink(Id LinkedEntityId,Id ContentDocumentId){
        return new ContentDocumentLink(LinkedEntityId = LinkedEntityId,ContentDocumentId = ContentDocumentId);
    }
    
    public static EmailTemplate queryEmailTemplate(){
        //return new EmailTemplate(Name = Name,DeveloperName = Name,Body = Body,Subject = Subject,FolderId = FolderId,TemplateType = TemplateType);
        List<EmailTemplate> template = [SELECT Id, Name, Body, Subject FROM EmailTemplate WHERE DeveloperName = :EM_Constants.OrderEmailTemplate];
        return template.get(0);
    }
    
    /*
     public static EmailTemplate queryEmailTemplate(String Name,String devName,String Body,String Subject,Id FolderId,String TemplateType){
        //return new EmailTemplate(Name = Name,DeveloperName = Name,Body = Body,Subject = Subject,FolderId = FolderId,TemplateType = TemplateType);
        List<EmailTemplate> template = [SELECT Id, Name, Body, Subject FROM EmailTemplate WHERE DeveloperName = :EM_Constants.OrderEmailTemplate];
        return template.get(0);
    }
     */
    
    public static Quote buildQuoteWithAccount(String quoteName,Id oppId,Id accountId, Id bankId, Id contactId){
        return new Quote(Name = quoteName,OpportunityId = oppId,ContactId = contactId,Customer__c = accountId, BankAccount__c = bankId);
    }
}