force-app/force-app/force-app/main/default/objects/Account/fields/BankAccount__c.field-meta.xml
<CustomField>
    <fullName>BankAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Bank Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>BankAccount__c.Name</field>
            <operation>notEqual</operation>
            <value>NULL</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BankAccount__c</referenceTo>
    <relationshipLabel>Customers</relationshipLabel>
    <relationshipName>Customers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/force-app/force-app/main/default/objects/Account/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>REPL</fullName>
            </value>
            <value>
                <fullName>CP</fullName>
            </value>
            <value>
                <fullName>WOS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/force-app/force-app/main/default/objects/Account/fields/Shipping_Country__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Shipping_Continent__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Burkina</fullName>
            </value>
            <value>
                <fullName>Burundi</fullName>
            </value>
            <value>
                <fullName>Cameroon</fullName>
            </value>
            <value>
                <fullName>Cape</fullName>
            </value>
            <value>
                <fullName>Central</fullName>
            </value>
            <value>
                <fullName>Chad (Tchad)</fullName>
            </value>
            <value>
                <fullName>Comoros</fullName>
            </value>
            <value>
                <fullName>Democratic</fullName>
            </value>
            <value>
                <fullName>Côte</fullName>
            </value>
            <value>
                <fullName>Djibouti</fullName>
            </value>
            <value>
                <fullName>Equatorial</fullName>
            </value>
            <value>
                <fullName>Egypt</fullName>
            </value>
            <value>
                <fullName>Eritrea</fullName>
            </value>
            <value>
                <fullName>Ethiopia</fullName>
            </value>
            <value>
                <fullName>Gabon</fullName>
            </value>
            <value>
                <fullName>The</fullName>
            </value>
            <value>
                <fullName>Ghana</fullName>
            </value>
            <value>
                <fullName>Kenya</fullName>
            </value>
            <value>
                <fullName>Lesotho</fullName>
            </value>
            <value>
                <fullName>Liberia</fullName>
            </value>
            <value>
                <fullName>Libya</fullName>
            </value>
            <value>
                <fullName>Madagascar</fullName>
            </value>
            <value>
                <fullName>Malawi</fullName>
            </value>
            <value>
                <fullName>Mali</fullName>
            </value>
            <value>
                <fullName>Mauritania</fullName>
            </value>
            <value>
                <fullName>Mauritius</fullName>
            </value>
            <value>
                <fullName>United States of America</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/force-app/force-app/main/default/objects/BankAccount__c/BankAccount__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <label>BankAccount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/force-app/force-app/main/default/objects/Opportunity/fields/Customer_Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Customer_Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/force-app/force-app/main/default/objects/Product2/fields/HSN_SAC_Code__c.field-meta.xml
<CustomField>
    <fullName>HSN_SAC_Code__c</fullName>
    <label>HSN/SAC Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/force-app/force-app/main/default/objects/Quote/fields/BankAccount__c.field-meta.xml
<CustomField>
    <fullName>BankAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>BankAccount</label>
    <referenceTo>BankAccount__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/force-app/force-app/main/default/objects/Quote/fields/Customer_Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Customer_Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/force-app/force-app/main/default/objects/Quote/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DOMESTIC</fullName>
            </value>
            <value>
                <fullName>OVERSEAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/force-app/force-app/main/default/objects/Quote/fields/Shipping_Country__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Shipping_Continent__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Burkina</fullName>
            </value>
            <value>
                <fullName>Burundi</fullName>
            </value>
            <value>
                <fullName>Cameroon</fullName>
            </value>
            <value>
                <fullName>Cape</fullName>
            </value>
            <value>
                <fullName>Central</fullName>
            </value>
            <value>
                <fullName>Chad (Tchad)</fullName>
            </value>
            <value>
                <fullName>Comoros</fullName>
            </value>
            <value>
                <fullName>Democratic</fullName>
            </value>
            <value>
                <fullName>Côte</fullName>
            </value>
            <value>
                <fullName>Djibouti</fullName>
            </value>
            <value>
                <fullName>Equatorial</fullName>
            </value>
            <value>
                <fullName>Egypt</fullName>
            </value>
            <value>
                <fullName>Eritrea</fullName>
            </value>
            <value>
                <fullName>Ethiopia</fullName>
            </value>
            <value>
                <fullName>Gabon</fullName>
            </value>
            <value>
                <fullName>The</fullName>
            </value>
            <value>
                <fullName>Ghana</fullName>
            </value>
            <value>
                <fullName>Kenya</fullName>
            </value>
            <value>
                <fullName>Lesotho</fullName>
            </value>
            <value>
                <fullName>Liberia</fullName>
            </value>
            <value>
                <fullName>Libya</fullName>
            </value>
            <value>
                <fullName>Madagascar</fullName>
            </value>
            <value>
                <fullName>Malawi</fullName>
            </value>
            <value>
                <fullName>Mali</fullName>
            </value>
            <value>
                <fullName>Mauritania</fullName>
            </value>
            <value>
                <fullName>Mauritius</fullName>
            </value>
            <value>
                <fullName>United States of America</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/force-app/force-app/main/default/objects/Quote/fields/Tax_For_Merchant__c.field-meta.xml
<CustomField>
    <fullName>Tax_For_Merchant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax For Merchant</label>
    <referenceTo>Tax_Code__c</referenceTo>
    <relationshipLabel>Quotes (Tax For Merchant)</relationshipLabel>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/force-app/force-app/main/default/objects/Quote/fields/UNLOADING_CHARGES__c.field-meta.xml
<CustomField>
    <fullName>UNLOADING_CHARGES__c</fullName>
    <defaultValue>0</defaultValue>
    <label>UNLOADING CHARGES</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/force-app/force-app/main/default/objects/QuoteLineItem/fields/Product_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Description__c</fullName>
    <label>Product Description</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/force-app/force-app/main/default/objects/QuoteLineItem/fields/QLI_Total_Price__c.field-meta.xml
<CustomField>
    <fullName>QLI_Total_Price__c</fullName>
    <label>Basic Unit Rate</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/force-app/force-app/main/default/objects/QuoteLineItem/fields/Tax_Code__c.field-meta.xml
<CustomField>
    <fullName>Tax_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tax Code</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.UoM__c</field>
            <operation>notEqual</operation>
            <value>null</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Tax_Code__c</referenceTo>
    <relationshipLabel>Quote Line Items</relationshipLabel>
    <relationshipName>Quote_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/force-app/force-app/main/default/objects/QuoteLineItem/fields/Taxable_Value__c.field-meta.xml
<CustomField>
    <fullName>Taxable_Value__c</fullName>
    <label>Taxable Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/force-app/force-app/main/default/objects/Tax_Code__c/Tax_Code__c.object-meta.xml
<CustomObject>
    <label>Tax Code</label>
    <nameField>
        <label>Tax Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tax Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/force-app/force-app/main/default/objects/Tax_Code__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Percent</type>
</CustomField>

force-app/force-app/force-app/main/default/classes/EM_QuoteLineItemsExtensionTest.cls
@isTest
public class EM_QuoteLineItemsExtensionTest {

    @IsTest
    static  void testControllerMethod() {
        
        BankAccount__c testBank = new BankAccount__c (Name = 'Test Bank');
        insert testBank;
        
        
        Account testAccount = new Account(Name = 'Test Account', Market__c = 'DOMESTIC', Category__c = 'CP',BankAccount__c = testBank.Id);
        insert testAccount;

        Id pricebookId = Test.getStandardPricebookId();
	Pricebook2 standardPricebook = new Pricebook2(
    	Id = pricebookId,
    	IsActive = true
	);
	update standardPricebook;
        
        Opportunity testOpportunity = new Opportunity(
            Name = 'Test Opportunity',
            StageName = 'Prospecting',
            CloseDate = Date.today(),
            AccountId = testAccount.Id,
            Pricebook2Id = standardPricebook.Id
        );
        insert testOpportunity;

        // Create a test Tax Code
        Tax_Code__c testTaxCode = new Tax_Code__c(Name = 'Test Tax Code', Rate__c = 10);
        insert testTaxCode;
        
        
       
        Product2 testProduct = new Product2(
            Name = 'Test Product',
            HSN_SAC_Code__c = '1234',
            ProductCode = 'PRD123'
        );
        insert testProduct;
        Pricebook2 testPricebook = new Pricebook2(Name = 'Test Pricebook', isActive = true);
        insert testPricebook;

		
        
		PricebookEntry standardPriceEntry = new PricebookEntry(
    		Pricebook2Id = standardPricebook.Id,
    		Product2Id = testProduct.Id,
    		UnitPrice = 50.00,
            IsActive = true
		);
		insert standardPriceEntry;
        
        Quote testQuote = new Quote(
            Name = 'test Quote',
            Tax_For_Merchant__c = testTaxCode.Id,
            UNLOADING_CHARGES__c = 2,
            OpportunityId = testOpportunity.Id,
            Shipping_Country__c = 'United States of America',
            Customer_Price_Book__c = standardPricebook.Id
        );
        insert testQuote;

		system.debug('Good So far2');

        // Create test QuoteLineItems
        QuoteLineItem testQLI1 = new QuoteLineItem(
            QuoteId = testQuote.Id,
            Product2Id = testProduct.Id,
            Sales_Price_after_Discount__c = 50,
            Taxable_Value__c = 40,
            QLI_Total_Price__c = 200,
            Quantity = 4,
            Tax_Amount__c = 20,
            PriceBookEntryId = standardPriceEntry.Id,
            UnitPrice = 50.00,
            Product_Description__c = 'Test'
        );
        insert testQLI1;

        

        Test.startTest();

        PageReference pageRef = Page.EM_QuoteTemplatePage; 
        pageRef.getParameters().put('id', String.valueOf(testQuote.Id));
        Test.setCurrentPage(pageRef);
        EM_QuoteLineItemsExtension controller = new EM_QuoteLineItemsExtension();
        
        System.assertEquals(0.00, controller.getTotalPrice());
		System.assertEquals(0, controller.getTotalQuantity());
        System.assertEquals(1, controller.getNextSerialNumber());
        System.assertEquals(0.00, controller.getTotalPriceWithoutTax());
        System.assertEquals(0.00, controller.gettotalUnitPrice());
        System.assertEquals(0.00, controller.getTotalIGSTAmount());
        System.assertEquals(0.00, controller.getTotalIGSTRate());
        System.assertEquals(false, controller.getIsCGST());
       	System.assertEquals(0.00, controller.getRounding());
        //System.assertEquals(' Zero Rupees Only', controller.getTotalTaxAmountInWords());
        //System.assertEquals(' Sixty Eight Rupees Only', controller.getTotalAmountInWords());
        System.assertEquals(true, controller.getIsDomesticAccount(),'Is Domestic');
        System.assertEquals(true, controller.getIsCP());
        System.assertEquals(true, controller.getIsUSCustomer());
        System.assertEquals(false, controller.getIsMerchant());
        System.assertEquals(0.00, controller.getRoundingForMerchant());
        // System.assertEquals(6.00, controller.getIGSTForMerchant());
        System.assertEquals('Test Tax Code 10.0%', controller.getTaxCodeForMerchant());

        Test.stopTest();
    }
    

}