force-app/force-app/force-app/main/default/objects/Account/fields/BankAccount__c.field-meta.xml
<CustomField>
    <fullName>BankAccount__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Bank Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>BankAccount__c.Name</field>
            <operation>notEqual</operation>
            <value>NULL</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>BankAccount__c</referenceTo>
    <relationshipLabel>Customers</relationshipLabel>
    <relationshipName>Customers</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/force-app/force-app/main/default/objects/BankAccount__c/BankAccount__c.object-meta.xml
<CustomObject>
    <label>Bank Account</label>
    <nameField>
        <label>BankAccount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/force-app/force-app/main/default/objects/Customers_Planned__c/Customers_Planned__c.object-meta.xml
<CustomObject>
    <label>Customers Planned</label>
    <nameField>
        <displayFormat>PC-{0000}</displayFormat>
        <label>Planned Customers Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customers Planned</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/force-app/force-app/main/default/objects/Customers_Planned__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Billing_District__c</field>
            <operation>equals</operation>
            <valueField>$Source.Place__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Customers Planned</relationshipLabel>
    <relationshipName>Customers_Planned</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/force-app/force-app/main/default/objects/Customers_Planned__c/fields/Place__c.field-meta.xml
<CustomField>
    <fullName>Place__c</fullName>
    <label>Place</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Adilabad</fullName>
            </value>
            <value>
                <fullName>Anantapur</fullName>
            </value>
            <value>
                <fullName>Chittoor</fullName>
            </value>
            <value>
                <fullName>East Godavari</fullName>
            </value>
            <value>
                <fullName>Alluri Sitarama Raju</fullName>
            </value>
            <value>
                <fullName>Anakapalli</fullName>
            </value>
            <value>
                <fullName>Annamaya</fullName>
            </value>
            <value>
                <fullName>Bapatla</fullName>
            </value>
            <value>
                <fullName>Eluru</fullName>
            </value>
            <value>
                <fullName>Guntur</fullName>
            </value>
            <value>
                <fullName>Kadapa</fullName>
            </value>
            <value>
                <fullName>Kakinada</fullName>
            </value>
            <value>
                <fullName>Konaseema</fullName>
            </value>
            <value>
                <fullName>Krishna</fullName>
            </value>
            <value>
                <fullName>Kurnool</fullName>
            </value>
            <value>
                <fullName>Manyam</fullName>
            </value>
            <value>
                <fullName>N T Rama Rao</fullName>
            </value>
            <value>
                <fullName>Nandyal</fullName>
            </value>
            <value>
                <fullName>Nellore</fullName>
            </value>
            <value>
                <fullName>Palnadu</fullName>
            </value>
            <value>
                <fullName>Prakasam</fullName>
            </value>
            <value>
                <fullName>Sri Balaji</fullName>
            </value>
            <value>
                <fullName>Sri Satya Sai</fullName>
            </value>
            <value>
                <fullName>Srikakulam</fullName>
            </value>
            <value>
                <fullName>Visakhapatnam</fullName>
            </value>
            <value>
                <fullName>Vizianagaram</fullName>
            </value>
            <value>
                <fullName>West Godavari</fullName>
            </value>
            <value>
                <fullName>Baksa</fullName>
            </value>
            <value>
                <fullName>Barpeta</fullName>
            </value>
            <value>
                <fullName>Bongaigaon</fullName>
            </value>
            <value>
                <fullName>Coimbatore</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/force-app/force-app/main/default/objects/Customers_Planned__c/fields/Tour_Plan__c.field-meta.xml
<CustomField>
    <fullName>Tour_Plan__c</fullName>
    <label>Tour Plan</label>
    <referenceTo>Tour_Plan__c</referenceTo>
    <relationshipLabel>Customers Planned</relationshipLabel>
    <relationshipName>Customers_Planned</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/force-app/force-app/main/default/objects/Tour_Plan__c/Tour_Plan__c.object-meta.xml
<CustomObject>
    <label>Tour Plan</label>
    <nameField>
        <displayFormat>TP-{00000}</displayFormat>
        <label>Tour Plan Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tour Plans</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/force-app/force-app/main/default/objects/Tour_Plan__c/fields/Continent__c.field-meta.xml
<CustomField>
    <fullName>Continent__c</fullName>
    <label>Continent</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Africa</fullName>
            </value>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>Europe</fullName>
            </value>
            <value>
                <fullName>North America</fullName>
            </value>
            <value>
                <fullName>South America</fullName>
            </value>
            <value>
                <fullName>Oceania</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/force-app/force-app/main/default/objects/Tour_Plan__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Continent__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Burkina</fullName>
            </value>
            <value>
                <fullName>Burundi</fullName>
            </value>
            <value>
                <fullName>Cameroon</fullName>
            </value>
            <value>
                <fullName>Cape</fullName>
            </value>
            <value>
                <fullName>Central</fullName>
            </value>
            <value>
                <fullName>Chad (Tchad)</fullName>
            </value>
            <value>
                <fullName>Comoros</fullName>
            </value>
            <value>
                <fullName>Democratic</fullName>
            </value>
            <value>
                <fullName>Côte</fullName>
            </value>
            <value>
                <fullName>Djibouti</fullName>
            </value>
            <value>
                <fullName>Equatorial</fullName>
            </value>
            <value>
                <fullName>Egypt</fullName>
            </value>
            <value>
                <fullName>Eritrea</fullName>
            </value>
            <value>
                <fullName>Ethiopia</fullName>
            </value>
            <value>
                <fullName>Gabon</fullName>
            </value>
            <value>
                <fullName>The</fullName>
            </value>
            <value>
                <fullName>Ghana</fullName>
            </value>
            <value>
                <fullName>Kenya</fullName>
            </value>
            <value>
                <fullName>Lesotho</fullName>
            </value>
            <value>
                <fullName>Liberia</fullName>
            </value>
            <value>
                <fullName>Libya</fullName>
            </value>
            <value>
                <fullName>Madagascar</fullName>
            </value>
            <value>
                <fullName>Malawi</fullName>
            </value>
            <value>
                <fullName>Mali</fullName>
            </value>
            <value>
                <fullName>Mauritania</fullName>
            </value>
            <value>
                <fullName>Mauritius</fullName>
            </value>
            <value>
                <fullName>Asia</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/force-app/force-app/main/default/objects/Tour_Plan__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Billing_District__c</field>
            <operation>equals</operation>
            <valueField>$Source.District__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Tour Plans</relationshipLabel>
    <relationshipName>Tour_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/force-app/force-app/main/default/objects/Tour_Plan__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Andhra Pradesh</fullName>
            </value>
            <value>
                <fullName>Assam</fullName>
            </value>
            <value>
                <fullName>Bihar</fullName>
            </value>
            <value>
                <fullName>Chhattisgarh</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>GOA</fullName>
            </value>
            <value>
                <fullName>Gujarat</fullName>
            </value>
            <value>
                <fullName>Haryana</fullName>
            </value>
            <value>
                <fullName>Jammu &amp; Kashmir</fullName>
            </value>
            <value>
                <fullName>Jharkhand</fullName>
            </value>
            <value>
                <fullName>Karnataka</fullName>
            </value>
            <value>
                <fullName>Kerala</fullName>
            </value>
            <value>
                <fullName>Madhya Pradesh</fullName>
            </value>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Odisha</fullName>
            </value>
            <value>
                <fullName>Pondicherry</fullName>
            </value>
            <value>
                <fullName>Punjab</fullName>
            </value>
            <value>
                <fullName>Punjab/Haryana</fullName>
            </value>
            <value>
                <fullName>Rajasthan</fullName>
            </value>
            <value>
                <fullName>Tamil Nadu</fullName>
            </value>
            <value>
                <fullName>Telangana</fullName>
            </value>
            <value>
                <fullName>Uttarakhand</fullName>
            </value>
            <value>
                <fullName>Uttar Pradesh</fullName>
            </value>
            <value>
                <fullName>West Bengal</fullName>
            </value>
            <value>
                <fullName>Himachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Ladakh</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/force-app/force-app/main/default/classes/TourPlanControllerTest.cls
@isTest
public class TourPlanControllerTest {
  @isTest
  public static void testGetCustomers() {
      BankAccount__c bank = new BankAccount__c(
          Name = 'Test Bank'
      );
      insert bank;
        Account acc = new Account(
            Name = 'Test Account',
            BankAccount__c = bank.Id,
            Billing_District__c = 'Coimbatore'
        );
        insert acc;
      
        // Create a Tour_Plan__c record
        Tour_Plan__c tourPlan = new Tour_Plan__c(
            
            Customer__c = acc.Id,
            Continent__c = 'Asia',
            Country__c = 'India',
            State__c = 'Tamil Nadu',
            District__c = 'Coimbatore'
        );
        insert tourPlan;

        // Call the method
        List<String> customerNames = TourPlanController.getCustomers(tourPlan.Id);

        // Verify the results
        System.assertEquals(1, customerNames.size(), 'Expected one customer name');
        system.assertEquals('TEST ACCOUNT', customerNames[0], 'Customer name should match');
    }

     @isTest
    public static void testGetTourPlanRecord(){
      BankAccount__c bank = new BankAccount__c(
          Name = 'Test Bank'
      );
      insert bank;
        Account acc = new Account(
            Name = 'Test Account',
            BankAccount__c = bank.Id,
            Billing_District__c = 'Coimbatore'
        );
        insert acc;
      
        // Create a Tour_Plan__c record
        Tour_Plan__c tourPlan = new Tour_Plan__c(
            
            Customer__c = acc.Id,
            Continent__c = 'Asia',
            Country__c = 'India',
            State__c = 'Tamil Nadu',
            District__c = 'Coimbatore'
        );
        insert tourPlan;

        // Call the method
        Tour_Plan__c tourPlanRec=TourPlanController.getTourPlan(tourPlan.Id);

        // Verify the results
        System.assertEquals('Coimbatore', tourPlanRec.District__c, 'Expected one customer name');
           
    }
    
    @isTest
    public static void testinsertPlannedCustomers(){
        BankAccount__c bank = new BankAccount__c(
          Name = 'Test Bank'
      );
        insert bank;
        Account acc = new Account(
            Name = 'Test Account',
            BankAccount__c = bank.Id,
            Billing_District__c = 'Coimbatore'
        );
        insert acc;
        
        acc = new Account(
            Name = 'Test Account 1',
            BankAccount__c = bank.Id,
            Billing_District__c = 'Coimbatore'
        );
        insert acc;

        
        
        // Create a Tour_Plan__c record
        List<String> accountNames = new List<String>{'Test Account', 'Test Account 1'};
        Tour_Plan__c tourPlan = new Tour_Plan__c(
           
            Customer__c = acc.Id,
            Continent__c = 'Asia',
            Country__c = 'India',
            State__c = 'Tamil Nadu',
            District__c = 'Coimbatore'
        );        
        
        String recordId = tourPlan.Id;
        insert tourPlan;
        
        // Call the method
       TourPlanController.insertPlannedCustomers(accountNames,tourPlan.Id);
       
        // Verify the expected results
        List<Customers_Planned__c> cpList = [SELECT Id, Customer__c, Place__c, Tour_Plan__c FROM Customers_Planned__c];
        System.assertEquals(2, cpList.size(), 'Incorrect number of Customers_Planned__c records inserted');

        for (Customers_Planned__c cp : cpList) {
            System.debug('Customer__c: ' + cp.Customer__c);
            System.assertEquals('Coimbatore', cp.Place__c, 'Incorrect Place__c on Customers_Planned__c');
            //System.assert(accountNames.contains(cp.Customer__c), 'Invalid Customer__c on Customers_Planned__c');
        }
  
        
    }
    
    
    @isTest
    public static void testSearchAllCustomers() {
         BankAccount__c bank = new BankAccount__c(
          Name = 'Test Bank'
      );
      insert bank;
        Account acc = new Account(
            Name = 'Test Account',
            BankAccount__c = bank.Id,
            Billing_District__c = 'Coimbatore'
        );
        insert acc;
        
         acc = new Account(
            Name = 'Test Account 1',
            BankAccount__c = bank.Id,
            Billing_District__c = 'Coimbatore'
        );
        insert acc;
      
        // Create a Tour_Plan__c record
        Tour_Plan__c tourPlan = new Tour_Plan__c(
            
            Customer__c = acc.Id,
            Continent__c = 'Asia',
            Country__c = 'India',
            State__c = 'Tamil Nadu',
            District__c = 'Coimbatore'
        );
        insert tourPlan;
        String recordId = tourPlan.Id;
        
        
        Test.startTest();
        // Call the method
        List<String> result = TourPlanController.searchAllCustomers('Test', recordId);
        Test.stopTest();

        // Verify the expected results
        System.assertEquals(2, result.size(), 'Incorrect number of matching objects');

        Set<String> expectedCustomerNames = new Set<String>{'TEST ACCOUNT', 'TEST ACCOUNT 1'};
        Set<String> actualCustomerNames = new Set<String>(result);

        System.assertEquals(expectedCustomerNames, actualCustomerNames, 'Mismatched customer names');
    }


}